// frontend/src/components/admin/UserTable.tsx
import { useState } from 'react'
import { Table, Pagination, Tag, Button, Dropdown } from '@arco-design/web-react'
import {
  IconEdit,
  IconEye,
  IconSafe,
  IconLock,
  IconUnlock,
  IconDelete,
  IconDown,
} from '@arco-design/web-react/icon'
import type { SysUser } from '@/models/entity'

interface UserTableProps {
  loading: boolean
  userList: SysUser[]
  total: number
  pageNum: number
  pageSize: number
  onEdit: (user: SysUser) => void
  onView: (user: SysUser) => void
  onResetPassword: (user: SysUser) => void
  onBlock: (user: SysUser) => void
  onUnblock: (user: SysUser) => void
  onDelete: (user: SysUser) => void
  onSizeChange: (size: number) => void
  onCurrentChange: (page: number) => void
}

const UserTable = ({
  loading,
  userList,
  total,
  pageNum,
  pageSize,
  onEdit,
  onView,
  onResetPassword,
  onBlock,
  onUnblock,
  onDelete,
  onSizeChange,
  onCurrentChange,
}: UserTableProps) => {
  const columns = [
    { title: 'ID', dataIndex: 'id', width: 80, align: 'center' as const },
    { title: '用户名', dataIndex: 'username', width: 120, ellipsis: true, tooltip: true },
    { title: '手机号', dataIndex: 'phone', width: 140 },
    { title: '邮箱', dataIndex: 'email', ellipsis: true, tooltip: true },
    {
      title: '角色',
      dataIndex: 'roles',
      width: 140,
      render: (record: SysUser) => (
        <Tag color={record.roles.includes('ROLE_ADMIN') ? 'red' : 'gray'}>
          {record.roles.includes('ROLE_ADMIN') ? '管理员' : '普通用户'}
        </Tag>
      ),
    },
    {
      title: '状态',
      dataIndex: 'status',
      width: 100,
      align: 'center' as const,
      render: (record: SysUser) => {
        if (record.status === 'NORMAL') return <Tag color="green">正常</Tag>
        if (record.status === 'LOCKED') return <Tag color="orange">锁定</Tag>
        return <Tag color="red">封禁</Tag>
      },
    },
    {
      title: '最后登录时间',
      dataIndex: 'lastLoginAt',
      width: 180,
      render: (dateString: string) => {
        if (!dateString) return '-'
        return new Date(dateString).toLocaleString('zh-CN')
      },
    },
    {
      title: '操作',
      width: 220,
      fixed: 'right' as const,
      render: (record: SysUser) => {
        const dropDownList = (
          <>
            <Dropdown.Item key="view" icon={<IconEye />}>查看详情</Dropdown.Item>
            <Dropdown.Item key="resetPwd" icon={<IconSafe />}>重置密码</Dropdown.Item>
            {record.status !== 'BANNED' ? (
              <Dropdown.Item key="block" icon={<IconLock />}>封禁用户</Dropdown.Item>
            ) : (
              <Dropdown.Item key="unblock" icon={<IconUnlock />}>解封用户</Dropdown.Item>
            )}
            <Dropdown.Item key="delete" style={{ marginTop: 4 }} icon={<IconDelete />}>删除用户</Dropdown.Item>
          </>
        )

        return (
          <Button.Group>
            <Button size="small" type="primary" icon={<IconEdit />} onClick={() => onEdit(record)}>
              编辑
            </Button>
            <Dropdown droplist={dropDownList} trigger="hover" onSelect={(key: string) => {
              switch (key) {
                case 'view': onView(record); break
                case 'resetPwd': onResetPassword(record); break
                case 'block': onBlock(record); break
                case 'unblock': onUnblock(record); break
                case 'delete': onDelete(record); break
              }
            }}>
              <Button size="small" secondary icon={<IconDown />}>
                更多
              </Button>
            </Dropdown>
          </Button.Group>
        )
      },
    },
  ]

  return (
    <div className="table-card">
      <Table
        columns={columns}
        data={userList}
        loading={loading}
        border
        stripe
        pagination={false}
        scroll={{ x: 1200 }}
      />
      <div className="pagination">
        <Pagination
          current={pageNum}
          pageSize={pageSize}
          total={total}
          pageSizeOptions={[10, 20, 50, 100]}
          showTotal
          showJumper
          onChange={(current, size) => {
            if (current !== pageNum) {
              onCurrentChange(current)
            }
            if (size !== pageSize) {
              onSizeChange(size)
            }
          }}
        />
      </div>
    </div>
  )
}

export default UserTable

// frontend/src/components/admin/UserTable.vue
<template>
  <a-card class="table-card">
    <a-table
      :data="userList"
      :loading="loading"
      border
      stripe
      class="user-table"
      :pagination="false"
    >
      <a-table-column title="ID" data-index="id" :width="80" align="center" />
      <a-table-column title="用户名" data-index="username" :width="120" ellipsis tooltip />
      <a-table-column title="手机号" data-index="phone" :width="140" />
      <a-table-column title="邮箱" data-index="email" ellipsis tooltip />
      <a-table-column title="角色" data-index="roles" :width="140">
        <template #cell="{ record }">
          <a-tag v-if="record.roles.includes('ROLE_ADMIN')" color="red">管理员</a-tag>
          <a-tag v-else color="gray">普通用户</a-tag>
        </template>
      </a-table-column>
      <a-table-column title="状态" data-index="status" :width="100" align="center">
        <template #cell="{ record }">
          <a-tag v-if="record.status === 'NORMAL'" color="green">正常</a-tag>
          <a-tag v-else-if="record.status === 'LOCKED'" color="orange">锁定</a-tag>
          <a-tag v-else color="red">封禁</a-tag>
        </template>
      </a-table-column>
      <a-table-column title="最后登录时间" data-index="lastLoginAt" :width="180">
        <template #cell="{ record }">
          {{ formatDateTime(record.lastLoginAt) }}
        </template>
      </a-table-column>
      <a-table-column title="操作" :width="220" fixed="right">
        <template #cell="{ record }">
          <a-button-group>
            <a-button
              size="small"
              type="primary"
              @click="handleEdit(record)"
            >
              <template #icon><IconEdit /></template>
              编辑
            </a-button>
            <a-dropdown @select="(cmd: string) => handleCommand(cmd, record)">
              <a-button size="small" type="secondary">
                更多<template #icon><IconDown /></template>
              </a-button>
              <template #dropdown>
                <a-doption value="view">
                  <template #icon><IconEye /></template>
                  查看详情
                </a-doption>
                <a-doption value="resetPwd">
                  <template #icon><IconSafe /></template>
                  重置密码
                </a-doption>
                <a-doption v-if="record.status !== 'BANNED'" value="block">
                  <template #icon><IconLock /></template>
                  封禁用户
                </a-doption>
                <a-doption v-else value="unblock">
                  <template #icon><IconUnlock /></template>
                  解封用户
                </a-doption>
                <a-doption value="delete" :style="{ marginTop: '4px' }">
                  <template #icon><IconDelete /></template>
                  删除用户
                </a-doption>
              </template>
            </a-dropdown>
          </a-button-group>
        </template>
      </a-table-column>
    </a-table>

    <a-pagination
      :current="pageNum"
      :page-size="pageSize"
      :total="total"
      :page-size-options="[10, 20, 50, 100]"
      show-total
      show-jumper
      class="pagination"
      @change="handlePageChange"
    />
  </a-card>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import {
  IconEdit,
  IconEye,
  IconSafe,
  IconLock,
  IconUnlock,
  IconDelete,
  IconDown
} from '@arco-design/web-vue/es/icon'
import type { SysUser } from '@/models/entity'

const props = defineProps<{
  loading: boolean
  userList: SysUser[]
  total: number
  pageNum: number
  pageSize: number
}>()

const emit = defineEmits<{
  edit: [user: SysUser]
  view: [user: SysUser]
  resetPassword: [user: SysUser]
  block: [user: SysUser]
  unblock: [user: SysUser]
  delete: [user: SysUser]
  sizeChange: [size: number]
  currentChange: [page: number]
}>()

const pageNum = computed({
  get: () => props.pageNum,
  set: (val) => emit('currentChange', val)
})

const pageSize = computed({
  get: () => props.pageSize,
  set: (val) => emit('sizeChange', val)
})

const formatDateTime = (dateString: string | undefined | null) => {
  if (!dateString) return '-'
  const date = new Date(dateString)
  return date.toLocaleString('zh-CN')
}

const handleEdit = (user: SysUser) => {
  emit('edit', user)
}

const handleCommand = (command: string, user: SysUser) => {
  switch (command) {
    case 'view':
      emit('view', user)
      break
    case 'resetPwd':
      emit('resetPassword', user)
      break
    case 'block':
      emit('block', user)
      break
    case 'unblock':
      emit('unblock', user)
      break
    case 'delete':
      emit('delete', user)
      break
  }
}

const handlePageChange = (current: number, pageSize: number) => {
  if (current !== pageNum.value) {
    emit('currentChange', current)
  }
  if (pageSize !== props.pageSize) {
    emit('sizeChange', pageSize)
  }
}
</script>

<style scoped>
.table-card {
  border-radius: 12px;
}

.user-table {
  margin-bottom: 20px;
}

.pagination {
  display: flex;
  justify-content: flex-end;
  margin-top: 20px;
}

:deep(.arco-tag) {
  font-weight: 500;
}

:deep(.arco-button-group) {
  display: inline-flex;
}
</style>
