// frontend/src/components/profile/BasicInfo.tsx
import { useState, useEffect } from 'react'
import { Form, Input, Radio, DatePicker, Button } from '@arco-design/web-react'
import message from '@arco-design/web-react/es/Message'
import dayjs from 'dayjs'

interface BasicInfoProps {
  username?: string
  initialData: {
    realName: string
    gender: 1 | 0
    birthday: string
    phone: string
    email: string
  }
  loading: boolean
  onSave: (data: any) => void
}

const BasicInfo = ({ username, initialData, loading, onSave }: BasicInfoProps) => {
  const [form] = Form.useForm()

  useEffect(() => {
    form.setFieldsValue({
      ...initialData,
      birthday: initialData.birthday ? dayjs(initialData.birthday) : undefined,
    })
  }, [initialData, form])

  const handleSave = async () => {
    try {
      const values = await form.validate()
      const birthdayStr = values.birthday ? values.birthday.format('YYYY-MM-DD') : ''
      onSave({
        realName: values.realName,
        gender: values.gender,
        birthday: birthdayStr,
        phone: values.phone,
        email: values.email,
      })
    } catch (error) {
      // 验证失败
    }
  }

  return (
    <Form form={form} className="info-form" style={{ maxWidth: 500 }}>
      <Form.Item label="用户名">
        <Input value={username} disabled />
      </Form.Item>
      <Form.Item label="真实姓名" field="realName" rules={[
        { minLength: 2, maxLength: 20, message: '真实姓名长度应在2-20个字符之间' },
      ]}>
        <Input placeholder="请输入真实姓名" />
      </Form.Item>
      <Form.Item label="性别" field="gender">
        <Radio.Group>
          <Radio value={1}>男</Radio>
          <Radio value={0}>女</Radio>
        </Radio.Group>
      </Form.Item>
      <Form.Item label="生日" field="birthday">
        <DatePicker format="YYYY-MM-DD" />
      </Form.Item>
      <Form.Item label="手机号" field="phone" rules={[
        { match: /^1[3-9]\d{9}$/, message: '电话号码格式不正确' },
      ]}>
        <Input placeholder="请输入手机号" />
      </Form.Item>
      <Form.Item label="邮箱" field="email" rules={[
        { type: 'email', message: '邮箱格式不正确' },
      ]}>
        <Input placeholder="请输入邮箱" />
      </Form.Item>
      <Form.Item>
        <Button type="primary" loading={loading} onClick={handleSave}>
          保存修改
        </Button>
      </Form.Item>
    </Form>
  )
}

export default BasicInfo

// frontend/src/components/profile/BasicInfo.vue
<template>
  <a-form ref="formRef" :model="form" class="info-form">
    <a-form-item label="用户名">
      <a-input :model-value="username" disabled/>
    </a-form-item>
    <a-form-item label="真实姓名" field="realName">
      <a-input v-model="form.realName" placeholder="请输入真实姓名"/>
    </a-form-item>
    <a-form-item label="性别" field="gender">
      <a-radio-group v-model="form.gender">
        <a-radio :value="1">男</a-radio>
        <a-radio :value="0">女</a-radio>
      </a-radio-group>
    </a-form-item>
    <a-form-item label="生日" field="birthday">
      <a-date-picker v-model="form.birthday" format="YYYY-MM-DD" />
    </a-form-item>
    <a-form-item label="手机号" field="phone">
      <a-input v-model="form.phone" placeholder="请输入手机号"/>
    </a-form-item>
    <a-form-item label="邮箱" field="email">
      <a-input v-model="form.email" placeholder="请输入邮箱"/>
    </a-form-item>
    <a-form-item>
      <a-button type="primary" :loading="loading" @click="handleSave">保存修改</a-button>
    </a-form-item>
  </a-form>
</template>

<script setup lang="ts">
import { ref, reactive, watch } from 'vue'

const props = defineProps<{
  username?: string
  initialData: {
    realName: string
    gender: 1 | 0
    birthday: string
    phone: string
    email: string
  }
  loading: boolean
}>()

const emit = defineEmits(['save'])

const formRef = ref()
const form = reactive({ ...props.initialData })

watch(() => props.initialData, (newVal) => {
  Object.assign(form, newVal)
}, { deep: true })

const rules = {
  realName: [{ minLength: 2, maxLength: 20, message: '真实姓名长度应在2-20个字符之间', trigger: 'blur' }],
  phone: [{
    match: /^1[3-9]\d{9}$/,
    message: '电话号码格式不正确',
    trigger: 'blur'
  }],
  email: [{type: 'email', message: '邮箱格式不正确', trigger: 'blur'}]
}

const handleSave = async () => {
  if (!formRef.value) return
  try {
    const valid = await formRef.value.validate()
    if (valid) {
      emit('save', { ...form })
    }
  } catch (error) {
    // 验证失败
  }
}
</script>

<style scoped>
.info-form {
  padding: 20px 0;
  max-width: 500px;
}
</style>
