// frontend/src/views/admin/SystemLog.vue
<template>
  <div class="system-log">
    <a-card class="log-card">
      <div class="log-header">
        <div class="title-section">
          <h2>系统日志</h2>
          <p class="subtitle">查看后台应用运行日志，仅管理员可访问</p>
        </div>
        <div class="actions">
          <a-select
            v-model="selectedFile"
            placeholder="选择日志文件"
            size="small"
            class="file-select"
            @change="loadLogs"
          >
            <a-option
              v-for="file in logFiles"
              :key="file"
              :label="file"
              :value="file"
            />
          </a-select>
          <span class="lines-label">行数：</span>
          <a-input-number
            v-model="lineCount"
            :min="50"
            :max="2000"
            :step="50"
            size="small"
          />
          <a-button type="primary" :loading="loading" @click="loadLogs">
            刷新
          </a-button>
        </div>
      </div>

      <a-divider />

      <a-empty v-if="!loading && logs.length === 0" description="暂无日志数据" />

      <a-scrollbar v-else class="log-content">
        <pre><code>{{ logsText }}</code></pre>
      </a-scrollbar>
    </a-card>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ArcoMessage } from '@/utils/arco-message'
import * as logApi from '@/api/system/log'

const loading = ref(false)
const logs = ref<string[]>([])
const lineCount = ref(200)
const logFiles = ref<string[]>([])
const selectedFile = ref<string>('')

const logsText = computed(() => logs.value.join('\n'))

const loadFiles = async () => {
  try {
    const res = await logApi.listLogFiles()
    if (res.code === 200) {
      logFiles.value = res.data || []
      if (!selectedFile.value && logFiles.value.length > 0) {
        selectedFile.value = logFiles.value[0]
      }
    } else {
      ArcoMessage.error(res.message || '加载日志文件列表失败')
    }
  } catch (error) {
    console.error('加载日志文件列表失败:', error)
    ArcoMessage.error('加载日志文件列表失败，请稍后重试')
  }
}

const loadLogs = async () => {
  loading.value = true
  try {
    const res = await logApi.listLatestLogs(lineCount.value, selectedFile.value || undefined)
    if (res.code === 200) {
      logs.value = res.data || []
    } else {
      ArcoMessage.error(res.message || '加载日志失败')
    }
  } catch (error) {
    console.error('加载系统日志失败:', error)
    ArcoMessage.error('加载系统日志失败，请稍后重试')
  } finally {
    loading.value = false
  }
}

onMounted(async () => {
  await loadFiles()
  await loadLogs()
})
</script>

<style scoped>
.system-log {
  padding: 20px;
}

.log-card {
  border-radius: 12px;
}

.log-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 16px;
}

.title-section h2 {
  margin: 0 0 8px 0;
  font-size: 22px;
  color: #303133;
}

.subtitle {
  margin: 0;
  font-size: 13px;
  color: #909399;
}

.actions {
  display: flex;
  align-items: center;
  gap: 8px;
}

.file-select {
  min-width: 200px;
}

.lines-label {
  font-size: 13px;
  color: #606266;
}

.log-content {
  margin-top: 12px;
  max-height: 600px;
  background-color: #1e1e1e;
  border-radius: 8px;
  padding: 12px;
}

pre {
  margin: 0;
  font-family: Consolas, Menlo, Monaco, 'Courier New', monospace;
  font-size: 12px;
  color: #d4d4d4;
  line-height: 1.5;
  white-space: pre-wrap;
}
</style>

// frontend/src/pages/admin/SystemLog.tsx
import { useState, useEffect } from 'react'
import { Card, Select, InputNumber, Button, Empty } from '@arco-design/web-react'
import message from '@arco-design/web-react/es/Message'
import * as logApi from '@/api/system/log'

const SystemLog = () => {
  const [loading, setLoading] = useState(false)
  const [logs, setLogs] = useState<string[]>([])
  const [lineCount, setLineCount] = useState(200)
  const [logFiles, setLogFiles] = useState<string[]>([])
  const [selectedFile, setSelectedFile] = useState<string>('')

  const logsText = logs.join('\n')

  const loadFiles = async () => {
    try {
      const res = await logApi.listLogFiles()
      if (res.code === 200) {
        setLogFiles(res.data || [])
        if (!selectedFile && (res.data || []).length > 0) {
          setSelectedFile(res.data![0])
        }
      } else {
        message.error(res.message || '加载日志文件列表失败')
      }
    } catch (error) {
      console.error('加载日志文件列表失败:', error)
      message.error('加载日志文件列表失败，请稍后重试')
    }
  }

  const loadLogs = async () => {
    setLoading(true)
    try {
      const res = await logApi.listLatestLogs(lineCount, selectedFile || undefined)
      if (res.code === 200) {
        setLogs(res.data || [])
      } else {
        message.error(res.message || '加载日志失败')
      }
    } catch (error) {
      console.error('加载系统日志失败:', error)
      message.error('加载系统日志失败，请稍后重试')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    loadFiles()
  }, [])

  useEffect(() => {
    if (selectedFile) {
      loadLogs()
    }
  }, [selectedFile, lineCount])

  return (
    <div className="system-log">
      <Card className="log-card">
        <div className="log-header">
          <div className="title-section">
            <h2>系统日志</h2>
            <p className="subtitle">查看后台应用运行日志，仅管理员可访问</p>
          </div>
          <div className="actions">
            <Select
              value={selectedFile}
              placeholder="选择日志文件"
              size="small"
              className="file-select"
              onChange={setSelectedFile}
              style={{ width: 200 }}
            >
              {logFiles.map((file) => (
                <Select.Option key={file} value={file}>
                  {file}
                </Select.Option>
              ))}
            </Select>
            <span className="lines-label">行数：</span>
            <InputNumber
              value={lineCount}
              onChange={setLineCount}
              min={50}
              max={2000}
              step={50}
              size="small"
            />
            <Button type="primary" loading={loading} onClick={loadLogs}>
              刷新
            </Button>
          </div>
        </div>

        <div style={{ margin: '16px 0', borderTop: '1px solid var(--color-border-2)' }} />

        {!loading && logs.length === 0 ? (
          <Empty description="暂无日志数据" />
        ) : (
          <div style={{ maxHeight: 600, backgroundColor: '#1e1e1e', borderRadius: 8, padding: 12, overflow: 'auto' }}>
            <pre style={{ margin: 0, fontFamily: 'Consolas, Menlo, Monaco, Courier New, monospace', fontSize: 12, color: '#d4d4d4', lineHeight: 1.5, whiteSpace: 'pre-wrap' }}>
              <code>{logsText}</code>
            </pre>
          </div>
        )}
      </Card>
    </div>
  )
}

export default SystemLog
